ALTER TABLE devices ADD COLUMN IF NOT EXISTS serial_port TEXT NOT NULL DEFAULT '';
ALTER TABLE devices ADD COLUMN IF NOT EXISTS baud_rate INTEGER NOT NULL DEFAULT 9600;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS parity VARCHAR(8) NOT NULL DEFAULT 'N';
ALTER TABLE devices ADD COLUMN IF NOT EXISTS data_bits INTEGER NOT NULL DEFAULT 8;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS stop_bits INTEGER NOT NULL DEFAULT 1;
